language: c
before_install:
- sudo apt-get update
- sudo apt-get -y install linux-headers-generic
install:
- uname -r
- ls /lib/modules
- make KERNELDIR=$(ls /lib/modules | head -1)/build
script:
- echo "No tests yet"
